version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb:10.11
    container_name: ecommerce-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ecommerce_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    command: ['--lower_case_table_names=1']
    ports:
      - "3306:3306"
