spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ecommerce_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: password
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        generate_statistics: true
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
logging:
  config: classpath:logback-local.xml
  level:
    org:
      hibernate:
        SQL: debug
    org.hibernate.type: trace
springdoc:
  cache:
    disabled: true
  override-with-generic-response: false