INSERT INTO USERS (ID, user_balance) VALUES (1, 100);
INSERT INTO USERS (ID, user_balance) VALUES (2, 200);
INSERT INTO USERS (ID, user_balance) VALUES (3, 300);

INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (1, 10, 'Product 1', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (2, 20, 'Product 2', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (3, 30, 'Product 3', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (4, 40, 'Product 4', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (5, 50, 'Product 5', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (6, 60, 'Product 6', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (7, 70, 'Product 7', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (8, 80, 'Product 8', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (9, 90, 'Product 9', 5);
INSERT INTO PRODUCTS(ID, PRICE, NAME, STOCK) VALUES (10, 100, 'Product 10', 5);

INSERT INTO CARTS (ID, USER_ID) VALUES (1, 1);
INSERT INTO CARTS (ID, USER_ID) VALUES (2, 2);
INSERT INTO CARTS (ID, USER_ID) VALUES (3, 3);