INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);

INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (10, 'Product 1', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (20, 'Product 2', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (30, 'Product 3', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (40, 'Product 4', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (50, 'Product 5', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (60, 'Product 6', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (70, 'Product 7', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (80, 'Product 8', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (90, 'Product 9', 5);
INSERT INTO PRODUCTS(PRICE, NAME, STOCK) VALUES (100, 'Product 10', 5);

INSERT INTO CARTS (USER_ID) VALUES (1);
INSERT INTO CARTS (USER_ID) VALUES (2);
INSERT INTO CARTS (USER_ID) VALUES (3);
INSERT INTO CARTS (USER_ID) VALUES (3);
INSERT INTO CARTS (USER_ID) VALUES (3);