INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);
INSERT INTO USERS (user_balance) VALUES (0);

INSERT INTO CARTS (USER_ID) VALUES (1);
INSERT INTO CARTS (USER_ID) VALUES (2);
INSERT INTO CARTS (USER_ID) VALUES (3);
INSERT INTO CARTS (USER_ID) VALUES (3);
INSERT INTO CARTS (USER_ID) VALUES (3);